/**
 * Copyright (C) 2024-2025 Gianmarco Lenzi
 * Licensed under MIT as part of the DSK Project, see LICENSE file for details.
 * A copy of the license can be found at: https://opensource.org/licenses/MIT.
 *
 * @file common.hpp
 * @author Gianmarco Lenzi
 * @brief Common header for testers.
 */

#pragma once
#include <string>
#include <vector>
#include <algorithm>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <iostream>

/**
 * @brief Namespace for logging.
 */
namespace Logging {}

/**
 * @brief Namespace for testers.
 */
namespace TesterLib {
    /**
     * @brief The type of warning messages generated by a test.
     */
    using TestWarnings = std::unordered_set<std::string>;

    /**
     * @brief The type of warning messages generated by a module.
     */
    using ModuleWarnings = std::unordered_map<std::string, TestWarnings>;

    /**
     * @brief The type of warning messages generated by a component.
     */
    using ComponentWarnings = std::unordered_map<std::string, ModuleWarnings>;
} // TesterLib
